### ISSUE TITLE
WTF IT WONT OPEN!!!1!!!!!!111!!!!11!1

### ISSUE THREAD

**Issue by StormiBear** [imchillin/Anamnesis#1095]
i have followed all the info on the faq. when i launch anamnesis it asks if i want to give it permission and i do and then nothing happenns after that. ive reinstalled it, run it as admin restarted my computer and done all the things that the help suggests :((((((((

**Comment by czl024** [comment]
I had the same issue, however, I manually downloaded and installed .NET 6.0.5 and it starts now. My settings has been reset after doing so but, otherwise, everything works smoothly. I have done a full uninstall and fresh reinstall of .NET 5.0.14 (as per the troubleshoot section of the wiki) to no avail before trying 6.0.5.

In short, (re)install .net 6.0.5 Desktop Runtime, **NOT** 5.0.14.

**Comment by StormiBear** [comment]
> I had the same issue, however, I manually downloaded and installed .NET 6.0.5 and it starts now. My settings has been reset after doing so but, otherwise, everything works smoothly. I have done a full uninstall and fresh reinstall of .NET 5.0.14 (as per the troubleshoot section of the wiki) to no avail before trying 6.0.5.
> 
> In short, (re)install .net 6.0.5 Desktop Runtime, **NOT** 5.0.14.

you saved me!!!!!!

**Comment by RageShoTT** [comment]
If that fixed your issue please close it thank you!
