### ISSUE TITLE
Colors bugged

### ISSUE THREAD

**Issue by Kelhsy** [imchillin/Anamnesis#1146]
Cannot change the color of eyes, skin, hair nor face paint

**Comment by RageShoTT** [comment]
we... might need a lot more then that to figure out what's going on, can you please post a log after that happens down here? 
[https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#accessing-log-files-for-issue-reporting](url)

**Comment by Kelhsy** [comment]
I just cannot change them as soon as I start the program, the colors just aren't there

**Comment by RageShoTT** [comment]
uhm oke
then please do this:
open anamnesis -> enter actor appearance
then please post here a screenshot of what you see and the last log created by anamnesis itself, you can find how to get it in the link i sent you before

**Comment by Kelhsy** [comment]
I get this error
 
![image](https://user-images.githubusercontent.com/66084462/176111770-748bf408-dedd-446f-b69e-495e6728bd7c.png)

[2022-06-28-09-43-39.txt](https://github.com/imchillin/Anamnesis/files/8998346/2022-06-28-09-43-39.txt)

**Comment by RageShoTT** [comment]
ohhhh you are using a very old version of Anamnesis, please download the lastest verison here:
https://github.com/imchillin/Anamnesis/releases
do remember that since the last two update Anamnesis requires .NET 6.0 so please install this aswell:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.6-windows-x64-installer

This should be enough

**Comment by chirpcodes** [comment]
This is a known issue and has been fixed for the next release. It's caused by TexTools having a lot of mods installed.

**Comment by Kelhsy** [comment]
Ah since I updated the program recently I thought I am on the newest build, but yeah I guess it's just mods then causing the issue
