### ISSUE TITLE
Rotation Sphere not showing in pose tab

### ISSUE THREAD

**Issue by Simusar** [imchillin/Anamnesis#1196]
New laptop, Windows 11, newest version of Anamnesis installed, when going into Gpose, and trying to reposition characters/limbs, the rotation orb tool is not visible, it can still be selected, but I am unable to see if/what I am clicking on
![Rotation Tool not displaying](https://user-images.githubusercontent.com/106941957/185726500-cb8c327e-7ca2-4c35-9fd6-93600052bcde.png)
.

**Comment by AsgardXIV** [comment]
You likely have Intel graphics, see #888 for more info on an updated driver or using your discrete graphics instead.

**Comment by Simusar** [comment]
Tried loading Anamnesis to a specific GPU - no change; updated GPU drivers - no change; installed version of .net listed on site - no change.

**Comment by Simusar** [comment]
downloaded, installed intel drivers from https://www.intel.ca/content/www/ca/en/download/19344/intel-graphics-windows-dch-drivers.html
rebooted - no change in Anamnesis
[2022-08-20-00-09-03.txt](https://github.com/imchillin/Anamnesis/files/9386417/2022-08-20-00-09-03.txt)
s

**Comment by Gajeel117** [comment]
Any updates coming with this? 
I've had the problem before and that Intel update fixed it, but it has been back since 6.2 and nothing I do will solve it.
Intel did a new update this morning which I hoped would fix it, but no luck. I have asked on the Discord, but no one seems to know.
I have tried as many variations of the .NET releases with no luck.
Gposing is honestly one of the few things I still play the game for, and without the sphere it makes it painful to do.

**Comment by Yuki-Codes** [comment]
This is a bug caused by intel 12th generation integrated GPU's. It is unfortunately not something we can fix. If you have a 12th gen intel processor, you can restore functionality by running anamnesis off of a dedicated GPU.

If you have a desktop computer, make sure all monitors are connected directly to your GPU, not your motherboard ports.
If you have a laptop with a discreet GPU, check your manufacturer guides on how to switch between GPUs.
If you have a laptop with only intel graphics, you will have to wait for intel to update their drivers to fix the issue.
