### ISSUE TITLE
Having the ability to set the type of 'Import' option you want as default in gpose

### ISSUE THREAD

**Issue by ivalith** [imchillin/Anamnesis#1240]
**Is your feature request related to a problem? Please describe.**
A problem I have is that when browsing through a folder of poses, it becomes frustrating to have to click the drop-down arrow and choose "body pose" (for example) for every single pose as I'm trying to find the one I want to use. For races outside of what the pose was made for, this becomes a frequent task due to the expressions usually displaying oddly. If I'm then flipping through expressions afterward, it also becomes a task of frequently having to choose expression every single time.

**Describe the solution you'd like**
I'd like to see the option of having a checkmark or something of that nature to tick after clicking the drop-down arrow on "Import" where you're given the option to choose between full transforms, body pose, etc.  that sets it as the current default way to import a pose so that after doing it the first time, every time I click "Import" afterward it continues to import what I'm choosing in the same way. So if I set the default to 'expression', every pose I imported would be imported as an expression until I left gpose or closed the app, whichever seems more appropriate for all end-users.

**Comment by Yuki-Codes** [comment]
This is something we are addressing in the [Anamnesis-Studio](https://github.com/XIV-Tools/Anamnesis-Studio) update with a new pose / file selector where the import options are remembered. (please look forward to it!) but it's unlikely to be implemented in the current Anamnesis version since the import choices are separate functions, and not a setting that can be remembered.
