### ISSUE TITLE
option to ignore validation warning of game client updates

### ISSUE THREAD

**Issue by Elypha** [imchillin/Anamnesis#1263]
Hello,

The official pre-built release of Anamnesis can likely work on CN client as well, but it seems that CN clients have never been validated by the tool, and the validation warning pops up every time the tool is launched.

It's not a big deal to just click `ok` and go on, but since most of the times the tool can work well on CN clients instead of just crash, I'm thinking of a solution to either additionally validate CN/KR clients (might be difficult for developers), or provide an option to bypass the game client check which CN/KR players can use to remove that warning from popping up a thousand times.

**Comment by Yuki-Codes** [comment]
Currently Anamnesis doesn't support the CN or KR client versions at all, any luck people have with it working is purely by accident. 

Nobody on the contributor list or development team has access to either alternative version to develop or test on. If someone with access to those clients wants to maintain Anamnesis for them, I _highly_ suggest forking the repository and maintaining an up-to-date version themselves. Especially since signatures and offsets for the En version are usually ahead of the CN/KR versions, it shouldn't be hard for someone to keep them working.

**Comment by Elypha** [comment]
Thanks for your reply.

I totally understand the circumstance that Anamnesis developers don't have access to CN/KR clients, and that Anamnesis isn't built with CN/KR compatibility in mind at all. However, I've been using the official release for more than a year, and I could say 95% of the times it worked as well, instead of just working very accidentally. This is why I hope to have such a feature and ask it in the official repo. (I guess that's why there isn't a popular fork for CN client since the official build is just fine)

An easy solution could be to add an option, or even a command line option (like `--no-client-validation`), to bypass the client check, as I assume it shouldn't require a time consuming rework of the code. I think it solves the whole problem on that aspect for CN/KR players, though it does no extra help to the international clients. What do you think of that?
