### ISSUE TITLE
Anamnesis

### ISSUE THREAD

**Issue by Jay3111** [imchillin/Anamnesis#1318]
![Screenshot_38](https://github.com/imchillin/Anamnesis/assets/138958688/4b57440a-9132-4b60-85f4-25f0583229aa)

I have downloaded and redownloaded this thing multiple times. Idk what’s going on. Please help if possible.

**Comment by Yuki-Codes** [comment]
you need to be in-game for Anamnesis to work, I'm not sure how you got past the initial process check without FFXIV running...

**Comment by Jay3111** [comment]
I went in game earlier. It just never pops up. 

> you need to be in-game for Anamnesis to work, I'm not sure how you got past the initial process check without FFXIV running...

**Comment by StoiaCode** [comment]
You need to start anamnesis AFTER already being in game.

You also need to start Ana as administrator and the game NOT as administrator, you should btw never ever do that anyway.

**Comment by Jay3111** [comment]
Ran it as an administrator in game and it still didn’t pop up

**Comment by Ani-ki** [comment]
Is Anamnesis generating a full log file? **[Follow this](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#accessing-log-files-for-issue-reporting)** to grab one and drag & drop the text file into a reply field (Github will do the rest).

Additionally, when you say 'pop up', are you checking in Task Manager to see if it's running at all?

I'm mildly concerned that the first thing to show up is 'Failed to read modlist'. But the log file will be more valuable to us than just a screenshot, since we need WAY more info to work from than what we've been given.

**Comment by Jay3111** [comment]
Never mind. I reset the settings. And it works now. Thank you!
