### ISSUE TITLE
Critical Error: UpdateService Error: Access to the path 'UpdateExtractor.exe' is denied.

### ISSUE THREAD

**Issue by ankanatchi** [imchillin/Anamnesis#1349]
**Describe the bug**
The program will not even open. It consistently gives me this error message and provides me with the option to close it. I have tried updating to the most recent version and the problem still occurs. It also occurs when I attempt to run older versions. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Attempt to open the program
2. See error

**Repeatability**
How often does the bug occur:
It is preventing me from using the program at all.

**Expected behaviour**
I expected the program to open as it normally does. 

**Log file**
I don't think there is one in this case? If I'm wrong please instruct me as to how I might retrieve this and I can do so.

**Comment by nztom** [comment]
I have a friend who had this issue.

It was caused by the temp directory
C:\Users\{your_username_here}\AppData\Local\Temp\AnamnesisUpdateLatest
being held open by something and the updater was failing to delete it.

To fix the issue they rebooted, then deleted the directory first thing.

After deleting the folder the issue went away.
