### ISSUE TITLE
Anamnesis doesn't open.

### ISSUE THREAD

**Issue by Civixia** [imchillin/Anamnesis#1352]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue.

**To Reproduce**
Steps to reproduce the behaviour:
when I try to click on the Anamnesis.exe I get a pop up from user account control, with I always get just press yes and then usually it opens up, now after that its just stops, it doenst open, don't get a error pop up or sound. I have FFXIV open, I tried with in gpose out of gpose. Restarting computer trying to open it with admin. and even deleted it and tried to redownload the newst link and turned off firewalls & virus scanner.

**Repeatability**
How often does the bug occur:
this started sins yesterday, the day before that it worked fine

**Comment by HinaVandercamp** [comment]
My Anamnesis will not open it just says Critical Error GameDataService Error: Failed to initialize Lumina (Are your game files up to date?) Is this just because of the new Final Fantasy XIV expansion or am i missing some files i need for the program to run i'm honestly confused. Or do i not have the new updated version or is there even one compatible yet?
![Anam Error Snippet](https://github.com/imchillin/Anamnesis/assets/174862533/dbbf5123-3eaa-45b1-a006-102dabecda32)

**Comment by technicallyTheatrical** [comment]
made an account just to say - check the discord, or use your eyes and look at the last update dates. the tool is broken as of 7.0, and it's being worked on. have patience, they're doing their best.

**Comment by HinaVandercamp** [comment]
I wasn’t in the discord I didn’t know. I just got to it no reason to be
rude about it I literally just got into the discord was about to remove the
question because I didn’t know. I didn’t even know if there was an update
or not.

**Comment by Iridius1** [comment]
If you bothered to check the issues list you'd actually know that somebody already asked. Do your goddamn due diligence before complaining about stuff not breaking.
