### ISSUE TITLE
After new update the face change into something weird when i use a pose

### ISSUE THREAD

**Issue by MissDani2** [imchillin/Anamnesis#1407]
**Describe the bug**
A clear and concise description of what the bug is, including how many times you encountered the issue.

**To Reproduce**
Steps to reproduce the behaviour:

**Repeatability**
How often does the bug occur:
Bug occured .../... attempts

**Expected behaviour**

**Log file**
Drag and drop the related log file(s) into the window, and they will be uploaded as part of your bug report. Please avoid using screenshots, as they very rarely provide any information of use to the developers. If your issue would benefit from additional evidence, such as a pose or appearance file, please package them into a `.zip` archive and upload them as well.

**Comment by StoiaCode** [comment]
[Faces](https://xivmodding.com/books/general-gposing/page/tips-for-dt-face-bone-posing)
Square Changed just about EVERYTHING about Faces. Something isnt working with faces? Chances are its just broken and you need to start learning from scratch.

Known things:
You WILL need to edit Position on Face bones now to achieve what you want now. Which will Limit the usuability within Anamnesis.
Poses are now specific for Faces. So optimaly a pose needs to be done for your exact face, which includes: Race -> Gender -> Face!
It is advised that you just use the in game Supplied Emotes for Expression before freezing in order to pose.
Bones with "prm" (Iris, Eye...) in their name will only work in GPose.
You can find tips on posing on our wiki: https://xivmodding.com/books/general-gposing/page/tips-for-dt-face-bone-posing

Theres nothing we can do about this. Just gotta start anew and learn!

**Comment by MissDani2** [comment]
it worked fine before anam got a new update 1 or 2 days ago but ty for the fast answer!

**Comment by ergoxiv** [comment]
Could you maybe be a bit more descriptive? You didn't fill out the template so I'm left wondering what exactly the issue is.

**Comment by MissDani2** [comment]
sorry i didnt really somehow understand the template ,im new on here ,its just when i pose by using my own pose or somebody elses new one the face glicthes into something creepy wich i tried to fix with the facebones but i couldnt so i thought it was a bug and asked for help, im gonna sent a picture with it ,it even happends on new poses. but ty for the help! =)

![2024-11-19_00-18-11-505_](https://github.com/user-attachments/assets/feb26a05-c5ce-46d2-a272-579a6e92d30b)

**Comment by MissDani2** [comment]
sorry i didnt really somehow understand the template ,im new on here ,its just when i pose by using my own pose or somebody elses new one the face glicthes into something creepy wich i tried to fix with the facebones but i couldnt so i thought it was a bug and asked for help, im gonna sent a picture with it to show what it does ,it even happends on new poses. but ty for the help! =)

![2024-11-18_19-27-56-396_](https://github.com/user-attachments/assets/18f3c3ec-f594-4e62-89ea-694e51fc77ed)

**Comment by ergoxiv** [comment]
1) How old is the pose file?
2) Are you trying to import a pose into your own character or an imported NPC appearance?
3) Which pose import option did you choose? The default one?

**Comment by MissDani2** [comment]
1: its a new pose file ( a pose i made)
2: it was an npc but it also does the same on my own character even with new files i made/ported in from somebody else (i know npc are kinda glitched atm)
3: the normal import option where you save your poses/ use dowloaded poses (older poses i know they glitch but not this bad wich i can normally easy fix)

**Comment by MissDani2** [comment]
could you please be more specific, how would this have something to do with SAID bug?, i dont see a green button because my anam color is purple since the day ive downloaded it (you can change the anam color), what you said issent really helping ,i know how to import poses and how to fix them but this is a new face bug wich i didnt had before,thanks for trying but i think your answers aren't really helping me. have a good day xx <3

**Comment by ergoxiv** [comment]
My comments aren't meant to be direct help. I am trying to gather information on a bug report that you submitted (this one) so that I can look into the issue. But without concrete details on what steps you're going through to trigger the problem, I won't be able to reproduce it and solve it.

The color of the button is not of importance. I cannot guess what color you've set your Anamnesis theme to. Sorry if that part confused you.

**Comment by CaptainSticky** [comment]
Perhaps if you provided the exact steps anyone could take to reproduce this, for example:

1. Be a <Gender> <Race> <Tribe>player, or Import NPC appearance using <NPC Name>
2. Enter GPOSE
3. Import pose using <Import Button> or <Import Body Pose> with <Which 3> check boxes checked.

Perhaps even providing the pose file you are attempting to pose with might help. Additionally, as Stoia mentioned initially, faces differ greatly between characters now. It's possible the pose file you're attempting to import was saved with a face different than the one your character is.
