### ISSUE TITLE
Relative bone transforms

### ISSUE THREAD

**Issue by Asche00** [imchillin/Anamnesis#286]
Advanced import does not seem to respect the parent bone rotation. This is especially noticeable for faces, which basically cannot currently be imported without going through extra steps to correct the head rotation.

Picture attached to explain in further detail:
![Advanced Import Issue](https://user-images.githubusercontent.com/82905226/115450659-d0ef7680-a1e1-11eb-8e9e-6f3fa1ad0a9b.png)

**Comment by Yuuki-Walsh** [comment]
Currently Anamnesis (And CMTool) store the bones in the same format the game memory does, relative to the characters root.

this means that when you load part of a pose, your getting those bones as if the rest of the character was also facing the same way as when the pose was made.

To solve this when loading expressions, CMTool resets the rotation of the head before loading the bones, then reapplies the head rotation.

To solve this fully in Anamnesis, bone rotations should be saved as rotations relative to their parents, thus when a partial pose is loaded, as long as the parenting information is the same, it should no longer break.

This work is required for partial pose support in non middy-based skeletons and generated skeletons for monsters.

**Comment by Yuuki-Walsh** [comment]
from #303
![Example](https://user-images.githubusercontent.com/82983781/115637754-cad2c600-a2c5-11eb-92a4-09012f737593.png)

**Comment by Yuuki-Walsh** [comment]
Update to this, now that we have full parenting information for all skeletons directly from game memory, we can be more confident in storing relative transforms regardless of what type of model is being posed (player, npc, mosnter, etc)

**Comment by Ani-ki** [comment]
Should be good to go as of the recent skeleton update.

**Comment by JSharpie** [comment]
Hi, it seems like it has gotten better but things could use improvement. I posted in #608  about using exact value

Here's a video again on my testing out the save and load this time going into more details and only using the mouth since that is the most noticable.
(still seems to be processing video but if you want to download instead but could finish processing by the time you get to see this ticket)
https://drive.google.com/file/d/1vNs3bNGgpwlDsO6jroJG8Mm8ruaFInhF/view?usp=sharing

0:00-1:15
Showing the scale of the mouth

1:17-1:38
Selecting a node changes the structure (this has nothing to do with the current issue, it's something i noticed while making the video)

1:40-
Restting the original emote structure and saving the entire thing

2:05
Resetting pose and pausing it

2:07
Loading expression

2:20
Double checking RPS marking 'x' that has not imported correct value

One thing I noticed that was consistent was that it isn't importing the scale to the value at all it defaults it to 1,1,1.

**Comment by JSharpie** [comment]
Hi, it seems like it has gotten better but things could use improvement. I posted in #608 about using exact value

Here's a video again on my testing out the save and load this time going into more details and only using the mouth since that is the most noticable.
(still seems to be processing video but if you want to download instead but could finish processing by the time you get to see this ticket)
https://drive.google.com/file/d/1vNs3bNGgpwlDsO6jroJG8Mm8ruaFInhF/view?usp=sharing

0:00-1:15
Showing the scale of the mouth

1:17-1:38
Selecting a node changes the structure (this has nothing to do with the current issue, it's something i noticed while making the video)

1:40-
Restting the original emote structure and saving the entire thing

2:05
Resetting pose and pausing it

2:07
Loading expression

2:20
Double checking RPS marking 'x' that has not imported correct value

One thing I noticed that was consistent was that it isn't importing the scale to the value at all it defaults it to 1,1,1.
