### ISSUE TITLE
Child player characters are broken in the Pose tab

### ISSUE THREAD

**Issue by solitonmedic** [imchillin/Anamnesis#290]
Using Pose mode on child player character models do not generate a proper skeleton on them, moving a bone just breaks the model entirely. 
Posing Matrix and GUI mode are disabled when editing child characters. Only the 3D view is available.

![image](https://user-images.githubusercontent.com/14916963/115463460-d658bb00-a1f9-11eb-914d-91347b27980b.png)

**Comment by Yuuki-Walsh** [comment]
it seems the skeleton generator has a hard time if your game isn't running at 60fps, and occasionally just gets it wrong anyway. We'll be packaging a built-in skeleton for more actors in the future, but you might need to just hit "regenerate skeleton" until it gets it right.

Generated skeletons don't work in the GUI or Matrix view.

**Comment by solitonmedic** [comment]
I went to a inn and I managed to get 60fps from there, but no luck, about 10 attempts in to regenerate a skeleton, but all came out a broken mess.

**Comment by Yuuki-Walsh** [comment]
I've generated (and named) a skeleton for young player models for the next release, so it wont ask to be generated anymore.

Since its a humanoid compatible skeleton with the same bone structure, it will now appear in Pose GUI and Pose Matrix, and poses made for players will also now work.

<sub><sub>I'm trusting the community here to not make me gouge out my eyes and take this way from them.</sub></sub>
