### ISSUE TITLE
Feature Request: undo/redo/reset

### ISSUE THREAD

**Issue by SkyAphid** [imchillin/Anamnesis#381]
It'd be nice for the poser if you could undo/redo/reset bones. Where reset would be to reset it back to what the base pose was (e.g. if you start with the battle stance, you can reset back to what the bone was originally set to). The reset function would be complex, but the undo/redo should be relatively simple. I can look into pulling and adding it myself if the team is too busy with other critical features right now.

**Comment by Yuuki-Walsh** [comment]
this has been on our radar, and I have tried to implement this previously, it gets complicated fast. You're welcome to give it a shot and pull request the changes in, otherwise I might try again once the other issues are sorted out.

It _should_ be as basic as saving the pose each time the user stops interacting with the transform editor and putting them in a queue, but there are some traps with toggling pose modes (physics, position, scale, etc).

**Comment by Agent-KI7KO** [comment]
Hi, perhaps a multi stage quicksave similar to CMTools, or an autosave setting each time you select a different entity (either a new model or a different part of the model).

**Comment by Yuki-Walsh** [comment]
We should look into utilizing the `MemoryBase` layer to track changes and propagate them up the memory hierarchy. We currently do this for the `ActorRefresh` attribute, so refactoring that to include the before/after values, and the property paths, shouldn't be too hard. Once a delay has passed (as with actor refresh), the changes from within an object should be stored into a history sheet for that object.

For posing, the undo stack would likely be on the actor skeleton memory? That way the undo would be per-actor-per-tab, undoing on the pose tab wont affect other actors unless they are tabbed to. This also avoids problems when actors have been removed.

**Comment by Yuki-Walsh** [comment]
This has been implemented for the next release.
