### ISSUE TITLE
.Net 5.0.7 - Anamnesis does not launch. 

### ISSUE THREAD

**Issue by feroxie** [imchillin/Anamnesis#409]
I am on windows 10 with .net 5.0.7 and the latest update will not push through. If I try to update via an older install, it does not update, and if I try a fresh install of the new release it will not open. Verified updating via old install does not work as the NPCs still load as small clothes off the old install so it is not updated.

**Comment by Ani-ki** [comment]
Just to confirm, have you followed the troubleshooting guide? Specifically, [Troubleshooting/Anamnesis silently fails to launch](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#anamnesis-silently-fails-to-launch).

**Comment by feroxie** [comment]
I had just installed 5.0.7 and did a second fresh install and that seemed to work. Not sure why but thanks!

**Comment by Yuuki-Walsh** [comment]
This is a bug with microsofts .Net 5.0.7 update as far as we can tell. It seems to fail to install correctly. Reinstalling .Net 5.0.7 seems to fix it.

**Comment by ZeroMaki** [comment]
I tried reinstalling many times restarting pc but it just doesn't launch at all

**Comment by Ani-ki** [comment]
@ZeroMaki can you please link to the version you believe is the correct one?

**Comment by Ani-ki** [comment]
I will assume since nobody else has had an issue with the version of .NET linked that it *was*, in fact, the correct version, and the person reporting an 'incorrect link' realised they'd actually downloaded the incorrect one and deleted their comments. 

In future, just admit you made a mistake instead of sending developers on wild goose chases, ZeroMaki.
