### ISSUE TITLE
Anamnesis will not start up properly

### ISSUE THREAD

**Issue by aetherial-night** [imchillin/Anamnesis#419]
I know game was just patched but figured this info may help in fixing things
Anamnesis will not run it seems, couldn't find some file information and tried several redownloads on the current version. before patch 5.57 it was working fine.

I tried fallback versions that did seem to work but what I think it was doing was continuously reloading. The GUI seemed to never allow me to do anything but pin an actor, there were no error messages in running these runs but I included the log file too. 
I hope this information is helpful, I never submitted any issue information before.
[anamesis error stuff.zip](https://github.com/imchillin/Anamnesis/files/6695585/anamesis.error.stuff.zip)

**Comment by Ani-ki** [comment]
It's not starting up properly because the tool has not been updated. 

Per the error message, this is because of the game being updated.

Please remember that we are just regular people, not machines, and we can't just update the tool the second the game is updated. We have personal lives to deal with first, and jobs we need to go to. Anamnesis is a project we work on in our free time, and as such, requires us to have free time first.

In future, **please be patient.**

**Comment by aetherial-night** [comment]
That is fine. I was just trying to be helpful. Totally understand everything.
