### ISSUE TITLE
Unable to do anything 

### ISSUE THREAD

**Issue by NevaehRose** [imchillin/Anamnesis#422]
I get a error message that says unsupported game version which always happens when there is a new patch but usually I can still use it. This time I cant. It launches just fine but then on the home screen it keeps flashing back and forth from World- unknown to world- the goble(thanalan) which is where I am. It also keeps flashing not signed in at the top. And because of this I can't do anything it won't even stay clicked on the character I want to be on.

**Comment by Mothism** [comment]
Hello. Due to the recent update to patch 5.57, there are several offsets that need to be updated for Anamnesis to work. Due to the fact that both developers live in Australia and work full time jobs, we ask that you exercise patience until they gain the opportunity to make the necessary updates. In the meantime, please consider joining the XIV Tools discord so you can get a notification on when those offsets are updated.

**Comment by Ani-ki** [comment]
This is due to us not having the time to update it on our end as yet. The error message you clicked though clearly states that game patches may break the tool and that updates may be needed.

Please be patient. I only finished work a few minutes ago and need time to get home and have lunch before I can do anything. Also, in future please look at other tickets both open and closed, becaise this has been covered several times, as well as spoken about in length on the XIV Tools Discord.

**Comment by NevaehRose** [comment]
Sorry I looked but I didn't see any open ones. Im new to all this I used to play on ps4. I know that things can happen because of new patches before you guys update it but me n a friend have been having problems off an on even before the patch. I wasn't posting to rush anyone, again I am very sorry if it seems that way. Have a good rest of ur day! 😁
