### ISSUE TITLE
Maintain changes in-game

### ISSUE THREAD

**Issue by Fivavoa** [imchillin/Anamnesis#442]
I'm aware this is a primarily a screenshot tool, but I actually really enjoy having this tool to mess around just playing as other races or styles for a little, especially with usually inaccessible styles. It usually unloads upon entering a loading zone or screen fade, so I was wondering if there could be some kind of permanent change akin to FFXI's [DressUp](https://github.com/Windower/Lua/tree/live/addons/DressUp)?

**Comment by Mothism** [comment]
This has already been addressed in the suggestions-box channel of the XIV Tools discord: there are no plans to implement this feature as it is a function Anamnesis is not capable of doing. As quoted from the channel pins: "Gear being carried across loading screens (teleporting etc.) - the developers have no plans for this feature as it doesn’t really fall within the scope of ‘screenshot tool’. Additionally doing anything that survives loading screens is dangerous since memory gets weird while loading." Please be sure to consult the pins in the suggestions-box in the future and make any unlisted suggestions in that channel!
