### ISSUE TITLE
Knees and calves not working as intended.

### ISSUE THREAD

**Issue by Vassagoxiv** [imchillin/Anamnesis#446]
The knees just move while moving nothing else. When moving a knee irl you move everything under hit. 
If I try to use "select children" I can move nothing. Everything is greyed out.

That issue has been there since Anamnesis has been available.

**Comment by Ani-ki** [comment]
@Vassagoxiv more info is required. Which screen are you on? Which leg are you editing?

(Also if this is an issue that has existed since Anamnesis first became available, it should have been reported well before now.)

**Comment by Ani-ki** [comment]
So this isn't actually a bug; while the user is correct in that in real life one bends their knee and not their calf, this order was chosen for compatibility reasons because that's the order in which they were implemented in CMTool and, since poses have already been released using Anamnesis and given its backwards compatibility, changing it now will be a pain down the track.

For that reason, it will not be changed.

**Comment by Vassagoxiv** [comment]
Still there's something in Anamnesis that should allow us to move the calve left and right and not just rotate it.
