### ISSUE TITLE
"light mode"?

### ISSUE THREAD

**Issue by eddievbalmung** [imchillin/Anamnesis#469]
Recently updated Anamnesis after the 5.58 patch, but now it looks like some sort of broken "light mode" instead of its normal appearance. 
![image](https://user-images.githubusercontent.com/87946325/126908974-f8c0bfc3-9250-4450-b639-dd1cce388f4e.png)

**Comment by eddievbalmung** [comment]
And the settings menu looks like this so if there IS a drop-down for the theme I can't see it. 
![image](https://user-images.githubusercontent.com/87946325/126909371-27e49ddc-99a9-491f-a69a-94f250208708.png)

**Comment by Mothism** [comment]
Per the recent update stated in the XIV Tools server: in order to allow for Windows 11 compatibility, the program was made to automatically default to your system's settings. Basically: if your Windows theme is in light mode, Anamnesis will be in light mode too. A fix will be released soon to allow an override for this default theme, so we ask for your patience. In the meantime, please consider joining the XIV Tools server so you can remain up to date with Anamnesis updates, as this has already been addressed there.

**Comment by Yuuki-Walsh** [comment]
Aditionaly, we've added theme overrides in the next version to get around this.
