### ISSUE TITLE
Screenshots are not getting safed

### ISSUE THREAD

**Issue by GosaDoragon** [imchillin/Anamnesis#495]
Hello i have installed Anamnesis after the guide and it does start but as soon as i use it to change anything on my charackter in ff14 i am not longer be able to take screenshots until i closed the enitre game and restarted it

**Comment by Ani-ki** [comment]
It is best practice to read the wiki, especially the Troubleshooting page, before opening tickets.

[**Your issue has been covered extensively already, and cannot be fixed by us as it's an issue with Windows itself.**](https://github.com/imchillin/Anamnesis/wiki/Troubleshooting#a-screenshot-failed-error-appears-when-using-anamnesis-in-conjunction-with-a-post-processing-tool-such-as-reshade-or-gshade)

**Comment by GosaDoragon** [comment]
i see thank you for your answere, i did manage to get it to work now
