### ISSUE TITLE
Cannot favorite monsters

### ISSUE THREAD

**Issue by Ani-ki** [imchillin/Anamnesis#558]
**Describe the bug**
Adding a monster or other model causes favourites to reset.

**To Reproduce**
Steps to reproduce the behaviour:
1. Add a model to favourites
2. Close Anamnesis
3. Reopen Anamnesis

**Expected behaviour**
The model should simply be added to the favourites list and not break.
As this was a feature added by a community developer, it is that original developer's responsibility to maintain the feature. In the meantime, the ability to add monsters to the favourites list will be removed.
Attn: @ajiiisai 

**Log file**
[2021-10-02-14-08-03.txt](https://github.com/imchillin/Anamnesis/files/7270850/2021-10-02-14-08-03.txt)

**Comment by Yuuki-Walsh** [comment]
This no longer causes favorites to reset. Now the mosnter items dont have the favorites button.

This issue is caused by favorites system storing both monsters and npc's as `INpcResident`, using `INpcResidentConverter` to serialize the type, however mosnters do nopt exist in teh NPC database and must be loaded from the monster database instead.

Aditionally, we currently have no way to reliable identify a monster in the monster database, the `Key` field is set sequentially, so any changes to the monster list will change the id's of all mosnters afterwards.

A likely solution is to serialize the apeparance fields (ModelType, Head, Body, Legs, Feet, Hands) of the monster instead of the Key, and search the mosnter list for matches (this might be slow, so probably want to generate a hashcode and put the monsters in a dictionary?)

**Comment by Ani-ki** [comment]
Fixed due to the changes to the NPC list system update.
