### ISSUE TITLE
Anamnesis crash when viewing character pages

### ISSUE THREAD

**Issue by CharonM72** [imchillin/Anamnesis#635]
**Describe the bug**
Anamnesis crashes when opening the Character page for certain unnamed (and probably also unmodelled) NPCs. It's not surprising, as these characters were never really meant to be viewed, but still Anamnesis probably should be handling it a bit more gracefully.
I have uploaded several logs of this event happening with different unnamed NPCs within Ul'dah. Note this does not occur with all unnamed NPCs, only sometimes (and even then not really consistently).

**To Reproduce**
Steps to reproduce the behaviour:
1. Pin an unnamed NPC character
2. Switch to the Character tab

**Expected behaviour**
Anamnesis should not crash.

**Log file**
[2021-11-18-08-25-48.txt](https://github.com/imchillin/Anamnesis/files/7563114/2021-11-18-08-25-48.txt)
[2021-11-18-08-34-38.txt](https://github.com/imchillin/Anamnesis/files/7563148/2021-11-18-08-34-38.txt)
[2021-11-18-08-32-19.txt](https://github.com/imchillin/Anamnesis/files/7563131/2021-11-18-08-32-19.txt)

**Comment by CharonM72** [comment]
I was also able to get this crash to occur by selecting Gilgamesh (from the Hildibrand quest line). It's possible at least one of the previous crashes were also from his character.
[2021-11-18-08-47-50.txt](https://github.com/imchillin/Anamnesis/files/7563269/2021-11-18-08-47-50.txt)

**Comment by Ani-ki** [comment]
This is being caused by a concurrent access issue with Lumina. It's been a thing that pops up every so often, and it's actually difficult to replicate, but we have a better grasp of what needs to be done here. 

Unfortunately, what needs to be done here is a rewrite of our Lumina access API to better support multithreading, which Lumina doesn't do natively. We'll aim for the next release.

**Comment by Yuuki-Walsh** [comment]
This has been fixed for the next release
