### ISSUE TITLE
Character deselection not clearing UI

### ISSUE THREAD

**Issue by zackoon49** [imchillin/Anamnesis#680]
**Describe the bug**
When entering or exiting castrum meridianum and the praetorium, anamnesis ceases gear function and I cant change my outfit.
Doesn't seem to happen anywhere else, at least not where I tested.

**To Reproduce**
1.  Change equipment with anamnesis.
2.  Enter or Exit any msq roulette related dungeon. Synced or UnSynced, doesn't matter.
3.  Swapping gear with anamnesis no longer works.

**Expected behaviour**
Uh. I think its supposed to work still.

**Extra notes**
This can be avoided by restarting the program after entering/exiting the MSQ, or... uh... entering gpose? for some reason if you use gpose and use a pose file, it makes the gear swapping work again.
Idk what it is, but i guess something about MSQ dungeons just doesn't agree with Anamnesis. I always knew they were cursed...

![Screenshot_1413](https://user-images.githubusercontent.com/96040090/145762704-8b8805ff-23c1-4000-b752-08d950905da5.png)

**Comment by AsgardXIV** [comment]
I've actually encountered this one before. There is a workaround. 

I can see in your screenshot that the character is not actually selected. All you need to do is click the "S.M." again on the actor list on the left there and it will work (or unpin/repin).

For some reason, when an unskippable cutscene plays it causes it to get deselected but the rest of the tool looks like it's working, so you can change gear and it looks like it changed but nothing happens. 

Hope that helps! Not sure what the root cause is though, seems like Anamnesis somehow loses track of the pinned actor and fails to match it again after the cutscene.

**Comment by Yuki-Walsh** [comment]
Yep looks like there is a bug when the actor is lost due to loading screens, the UI should be cleared but its still showing the old values.

**Comment by Yuki-Walsh** [comment]
We've fixed the bug that was preventing the UI from clearing correctly for the next build.
It should b emuch clearer whats happening in future.
