### ISSUE TITLE
Jaw bone moves when selecting it if the starting pose is not idle

### ISSUE THREAD

**Issue by AsgardXIV** [imchillin/Anamnesis#720]
**Describe the bug**
So this is a bit of an odd one but when you start or load a pose for Hrothgar or Viera the jaw (j_ago) moves slightly.

It's most obvious with Hroth where the movement is pretty large but it does also happen subtly with Viera. No other race is affected that I can tell. It happens at the point you select the first bone (even an unrelated one) in the tool, or when you load a pose (I assume loading is somehow "touching" the bone like selecting one does).

My guess is that it's something to do with the fact they have the extra face bones but beyond that I have no idea why.

**To Reproduce**
Steps to reproduce the behaviour:
1. Be a Hrothgar
2. Enter GPose and Freeze
3. Note the position of the jaw
4. Enable posing 
5. Click on any bone in the GUI view but make no change
6. Notice that the Jaw of the character closes slightly

**Expected behaviour**
The jaw should remain in the same position (or at least very close).

**Comment by Ani-ki** [comment]
I'm assuming PR #719 is the fix for this? I'm just going through the PRs now!

**Comment by Yuki-Walsh** [comment]
Looks like this does affect all races, but its most obvious when the pose you're starting from has the mouth open, such as /laugh.

**Comment by Yuki-Walsh** [comment]
update: looks like the real underlying cause was that the game actually has 2 jaw bones, one is part of the head, and one is part of the torso, this is because the game animates those two parts seperately. In our case we were reading the jaw bone from the torso and writing it to the head, and in some poses those values did not match.

I have updated it to read the value from the head and write it to the torso instead.

Fixed for next release.
