### ISSUE TITLE
Facial Bones Rotations can break when rotating Neck or Head bones.

### ISSUE THREAD

**Issue by Maxunit** [imchillin/Anamnesis#727]
**Describe the bug**
Facial Bones rarely tend to move whenever you move the Neck or Head Bone along any of the 3 axes. The value increments are minimal at first, but tend to pile up. In very rare cases, it can happen with the values increasing a lot. (like the lips suddenly being all broken)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go into GPose.
2. Freeze actor and either load a pose or work with the pose you are already in.
3. Rotate the Neck and/or Head bone around any of the 3 axes and then look at the lip or jaw bones as an example. Those bones "flicker" a lot and it can happen, that they do not snap back in place properly and instead remain at a wrong position.

**Expected behaviour**
This should not happen.

**Log file**
No Log file available as of now. Will investigate further and upload one whenever it happens.

**Comment by ThaddeusCleaver** [comment]
I can confirm this is still happening--and if anything has gotten even touchier/worse.

**Comment by ThaddeusCleaver** [comment]
The 12-23-2021 Build is the last build not to have this issue

**Comment by ThaddeusCleaver** [comment]
The 12-23-2021 Build does in fact seem to be have this problem occur slower.

**Comment by ThaddeusCleaver** [comment]
Please prioritize this ASAP. It makes the newest build basically unusable.

**Comment by Ani-ki** [comment]
Sorry @ThaddeusCleaver, we have other stuff to prioritise. You could help by actually supplying information to help us investigate, since we're not having this issue on our end. 

We don't appreciate this kind of rudeness. Please respect the fact that we have real lives to deal with and work on this for fun.

**Comment by ThaddeusCleaver** [comment]
> Sorry @ThaddeusCleaver, we have other stuff to prioritise. You could help by actually supplying information to help us investigate, since we're not having this issue on our end.
> 
> We don't appreciate this kind of rudeness. Please respect the fact that we have real lives to deal with and work on this for fun.

I wasn't trying to be rude--I really do find it that debilitating to using the program at it's worst. If anything now I'm just baffled that it's not happening on your side. Further testing suggests to me that framerate might be a big part of the issue. The main area I was having this happen consistently in was Radz-at-Han, with Old Sharlayan being the second-worst example, both areas that have had their framerates tanked by sheer traffic lately. 

This is compounded by use of Gshade, which has shaders I use when preparing screenshots that further lower the framerate. I've attached a log of a session I just conducted where, even in Limsa upper at off-peak hours, however, the issue still occurred after being tabbed/having the discord overlay open for a short period with some of said shaders active. I believe it's happening where the 'Failed to find best HkaSkeleton for partial skeleton' lines are, but otherwise I'm not literate enough in the program's language to divine specifics. 

[2022-01-06-08-46-32.txt](https://github.com/imchillin/Anamnesis/files/7822252/2022-01-06-08-46-32.txt)

I apologize if my previous comments came off as rude despite intention. I didn't mean to sound accusatory, I was merely speculating. I'll try and keep an eye out for more egregious examples of it happening to provide further logs.

**Comment by bonziie** [comment]
Hi, I've been able to replicate this issue - here's a recording of it. I've also attached the log file. I've disabled GShade as well, and it seems like it's only happening when I move the head and neck bones.

[2022-01-09-12-26-04.txt](https://github.com/imchillin/Anamnesis/files/7834349/2022-01-09-12-26-04.txt)
Recording: https://youtu.be/ce8TPAaMumQ

 I've also experienced the "flickering" in point 3 of the OP on parts that aren't the neck or head bones (such as hair front left and eyes).
