### ISSUE TITLE
Unable to pose minions/mobs, and Unique NPCs not loading in Gpose

### ISSUE THREAD

**Issue by kurorekku** [imchillin/Anamnesis#734]
Description.
Ive recently updated Anam and realized it no longer detects and automatically generate bones for pets, minions and other monster/bosses, was this function taken away or is there still ways to pose them? 

Ive also tried using my friends and their carbuncles as stand-ins in gposes while loading unique NPC appearance on them (e.g. Yugiri, Lyse, etc) but the appearance doesnt stay on the players and they end up with random facial features upon entering gpose. The issue only occurs to players though, carbuncles retains the unique NPC's look. (e.g. I can load Emet on a Carbuncle just fine, but on a player, they would look like a random Elezen upon entering Gpose)

For the NPC/GPose issue
Steps to reproduce the behaviour:
1. Add a new actor (in this case, my friend, and their carbuncle.
2. Select NPC, search Emet-Selch. Apply appearance on Player (friend). Do the same with the Carbuncle. Both the players and Carbuncle now look like Emet Selch.
3. Enter gpose. 
4. Carbuncle retains the unique NPC's appearance, but the player does not, and ends up having random elezen features. (They were a Viera beforehand).

**Expected behaviour**
When entering GPose, the player is supposed to look like the selected NPC.

Second issue:
1. Add actor, select Carbuncle.
2. Change Carbuncle appearance to Ifrit.
3. Enter Gpose, and into the 3D view of the pose menu.
4. The Carbuncle/Ifrit does not have any bones generated and cannot be posed.

Expected Result:
Prior to updating Anamnesis, all the previous issues I had did not exist and work the way I intended to. The carbuncles, minions, and almost every monster/boss models had bones generated and were poseable.

**Comment by Ani-ki** [comment]
Posing monsters (including minions and mounts) should be working as normal, but I will doublecheck when I'm at home at my PC.

Regarding NPC appearances, **[they will only retain their unique appearances if loaded onto yourself or a Carbuncle.](**url**)** Other actors, including other players, will not keep them when entering GPose. This is unfortunately an engine limitation we are unable to get around.

**Comment by skydarkreign** [comment]
i am having trouble to

my NPC load fine But when i enter gpose is says i must dis able char motion  when i select them and will not let me change their pose like  it did before the patch
![Capture](https://user-images.githubusercontent.com/73044347/147619232-79264493-457f-4cab-b85c-27c81d842b7f.PNG)
g                                                     i cant edit the npc at all it wont even target her like it did before the patch

**Comment by skydarkreign** [comment]
and yes i had all motion dis abled

**Comment by skydarkreign** [comment]
so please fix it like it was before

**Comment by skydarkreign** [comment]
you can see better from this screen shot notice my char is in the orange around my name but the npc is red i can alter my char but not the npc

![Capture 2](https://user-images.githubusercontent.com/73044347/147619891-0a56674e-4228-40b0-855b-e2989de3d4e8.PNG)

**Comment by skydarkreign** [comment]
the upper sc shows it can on my char but the on below it show that she has nothing  and her initials are in red and give that message

![Capture 3](https://user-images.githubusercontent.com/73044347/147620096-f1a6d535-2d74-4d26-8cb1-49e901b128b5.PNG)

**Comment by skydarkreign** [comment]
so please fix it like it was before the patch

**Comment by Ani-ki** [comment]
Okay so we have a few issues here, @skydarkreign.

First of all, you should be making your own ticket for your own issues, not piggybacking on a totally unrelated issue. Please refrain from posting on this ticket unless you are experiencing the same issues. And you absolutely do NOT need to be spamming a ticket if you report your issues correctly, as outlined in the instructions, which I'm going out on a limb here and assuming you haven't read.

Secondly, you seem to have a fundamental misunderstanding of how the tool works. I'm not sure what you were using prior, but **we have made absolutely no changes to that function since September**, so there's nothing for us to 'fix'. Especially when I can *see* from your screenshots that *you do not have motion disabled.* **This is entirely user error on your part.**

Thirdly, **we do not take kindly to people making demands of us** when they have absolutely no clue what they're talking about. You have made it abundantly obvious that you haven't done the bare minimum and even read our documentation. Do not expect us to respect your request if you cannot do the bare minimum and show us as the developers the resepct we deserve for making this free tool.
